# Generated by Django 4.2.2 on 2023-07-22 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_borrower'),
    ]

    operations = [
        migrations.RenameField(
            model_name='borrower',
            old_name='user',
            new_name='book',
        ),
    ]
